INCFLAGS += -I 	./vecmath/include/

LINKFLAGS  = -lglut -lGL -lGLU -lGLEW
#LINKFLAGS += -L /mit/6.837/public/lib -lvecmath

CFLAGS    = -g3 -Wall
CC        = g++
SRCS      = $(wildcard ./src/*.cpp)
#SRCS     += $(wildcard vecmath/src/*.cpp)
OBJS      = $(SRCS:.cpp=.o)
PROG      = glviewer

all: $(SRCS) $(PROG)

$(PROG): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@ $(INCFLAGS) $(LINKFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -c -o $@ $(INCFLAGS)

depend:
	makedepend $(INCFLAGS) -Y $(SRCS)

clean:
	rm $(OBJS) $(PROG)


